name: flutter driver

on: 
   push:
      branches:
         - master
   pull_request:
     

jobs:
  drive:
    runs-on: macos-latest
    timeout-minutes: 40
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any        
      # matrix job fails.
      fail-fast: false
      matrix:
        api-level: [21, 28, 30] # [minSdk, most used, newest] 19 would be minSDK but does not support x86_64
        target: [google_apis] # [default, google_apis]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
        flutter-version: '1.22.5'
    - run: "flutter --version"
    - run: "flutter pub get"
    - run: "flutter build apk --debug"

    - name: "List all test files"
      run: "ls -R test_driver"

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: "flutter driver --dart-define=testing_mode=true --target=test_driver/run_all.dart"

