name: flutter driver

on: 
   push:
#      branches:
#         - master
   pull_request:
     

jobs:
  drive:
    runs-on: macos-latest
    strategy:
      # When set to true, GitHub cancels all in-progress jobs if any        
      # matrix job fails.
      fail-fast: false
      matrix:
        api-level: [18, 28, 29] # [minSdk, most used, newest]
        target: [default] # [default, google_apis]
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: "flutter pub get"
    - run: "flutter build apk --release"

    - name: "List all test files"
      run: "ls -R test_driver"

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        #arch: x86_64
        #profile: Nexus 6
        script: "flutter drive --target=test_driver/run_all.dart"

